---
editor: code
repo_path: ~none
navigator_url: https://navigator.wethinkcode.co.za
username : a@student.wethinkcode.co.za
review_manager_url: https://review-manager.wethinkcode.co.za
keycloak_url: https://keycloak.wethinkcode.co.za